// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CameraStream.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CAMERASTREAM_H_
#define _FAST_DDS_GENERATED_CAMERASTREAM_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CameraStream_SOURCE)
#define CameraStream_DllAPI __declspec( dllexport )
#else
#define CameraStream_DllAPI __declspec( dllimport )
#endif // CameraStream_SOURCE
#else
#define CameraStream_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CameraStream_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure CameraStream defined by the user in the IDL file.
 * @ingroup CAMERASTREAM
 */
class CameraStream
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CameraStream();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CameraStream();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CameraStream that will be copied.
     */
    eProsima_user_DllExport CameraStream(
            const CameraStream& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CameraStream that will be copied.
     */
    eProsima_user_DllExport CameraStream(
            CameraStream&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CameraStream that will be copied.
     */
    eProsima_user_DllExport CameraStream& operator =(
            const CameraStream& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CameraStream that will be copied.
     */
    eProsima_user_DllExport CameraStream& operator =(
            CameraStream&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CameraStream object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CameraStream& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CameraStream object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CameraStream& x) const;

    /*!
     * @brief This function sets a value in member time_stamp
     * @param _time_stamp New value for member time_stamp
     */
    eProsima_user_DllExport void time_stamp(
            uint64_t _time_stamp);

    /*!
     * @brief This function returns the value of member time_stamp
     * @return Value of member time_stamp
     */
    eProsima_user_DllExport uint64_t time_stamp() const;

    /*!
     * @brief This function returns a reference to member time_stamp
     * @return Reference to member time_stamp
     */
    eProsima_user_DllExport uint64_t& time_stamp();

    /*!
     * @brief This function sets a value in member buf_index
     * @param _buf_index New value for member buf_index
     */
    eProsima_user_DllExport void buf_index(
            int32_t _buf_index);

    /*!
     * @brief This function returns the value of member buf_index
     * @return Value of member buf_index
     */
    eProsima_user_DllExport int32_t buf_index() const;

    /*!
     * @brief This function returns a reference to member buf_index
     * @return Reference to member buf_index
     */
    eProsima_user_DllExport int32_t& buf_index();

    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::vector<char>& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::vector<char>&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::vector<char>& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::vector<char>& message();
    /*!
     * @brief This function sets a value in member fps
     * @param _fps New value for member fps
     */
    eProsima_user_DllExport void fps(
            float _fps);

    /*!
     * @brief This function returns the value of member fps
     * @return Value of member fps
     */
    eProsima_user_DllExport float fps() const;

    /*!
     * @brief This function returns a reference to member fps
     * @return Reference to member fps
     */
    eProsima_user_DllExport float& fps();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const CameraStream& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint64_t m_time_stamp;
    int32_t m_buf_index;
    std::vector<char> m_message;
    float m_fps;
};

#endif // _FAST_DDS_GENERATED_CAMERASTREAM_H_